name: Build Go Android AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone SoundCloud API
      run: git clone https://github.com/zackradisic/soundcloud-api.git

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install Android SDK and NDK (without sdkmanager)
      run: |
        # Install dependencies for downloading and unzipping
        sudo apt-get update
        sudo apt-get install -y wget unzip

        # Download Android SDK tools
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip
        mkdir -p $HOME/android-sdk
        unzip android-sdk-tools.zip -d $HOME/android-sdk
        rm android-sdk-tools.zip

        # Download Android Platform and NDK manually
        wget https://dl.google.com/android/repository/platform-tools_r31.0.3-linux.zip -O platform-tools.zip
        unzip platform-tools.zip -d $HOME/android-sdk
        rm platform-tools.zip

        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip -O android-ndk.zip
        unzip android-ndk.zip -d $HOME/android-sdk
        rm android-ndk.zip

        # Set environment variables
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/ndk-bundle:$PATH" >> $GITHUB_ENV

        # Verify installation
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
        echo "PATH=$PATH"

    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init || echo "Gomobile already initialized"

    - name: Build AAR
      run: |
        cd soundcloud-api
        gomobile bind -target=android -o soundcloud.aar

    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: soundcloud-android
        path: soundcloud-api/soundcloud.aar
