name: Build Go Android Library

env:
  CI: true

on:
  workflow_dispatch:   # Ermöglicht manuelle Auslösung über GitHub UI

jobs:
  build:
    name: Build Android Library
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Android SDK and NDK
        run: |
          # Install Android SDK and NDK using the SDK manager
          sudo apt-get update
          sudo apt-get install -y unzip

          # Download Android Command Line Tools (latest stable)
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d /usr/local/android-sdk

          # Set environment variables
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH

          # Install Android SDK components using sdkmanager
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "ndk;21.3.6528147" "platforms;android-21"

          # Set ANDROID_NDK_HOME to the installed NDK location
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147

      - name: Install GoMobile
        run: |
          # Install GoMobile
          go install golang.org/x/mobile/cmd/gomobile@latest
          # Initialize GoMobile (creates necessary Android setup)
          gomobile init

      - name: Get Go dependencies
        run: |
          # Download Go dependencies
          go get -v -t -d ./...

      - name: Build Go Android Library (AAR)
        run: |
          # Use gomobile to bind the Go code to an Android AAR file
          gomobile bind -v -o mylibrary.aar .

      - name: Test Go code
        run: |
          # Run Go tests if you have any
          go test -v ./soundcloudapi_test

      - name: Upload Android Library AAR file
        uses: actions/upload-artifact@v3  # Update to the latest version of upload-artifact
        with:
          name: android-library
          path: mylibrary.aar
