name: Build Go Android AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone SoundCloud API
      run: git clone https://github.com/zackradisic/soundcloud-api.git

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install Android SDK and NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk/cmdline-tools
        rm commandlinetools-linux-7583922_latest.zip
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV

        sdkmanager --version

        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "ndk;21.4.7075529" "build-tools;30.0.3"

    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init || echo "Gomobile already initialized"

    - name: Build AAR
      run: |
        cd soundcloud-api
        gomobile bind -target=android -o soundcloud.aar

    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: soundcloud-android
        path: soundcloud-api/soundcloud.aar
