name: Build Go Android AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone SoundCloud API
      run: git clone https://github.com/zackradisic/soundcloud-api.git

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: /tmp/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Build AAR
      run: |
        cd soundcloud-api
        gomobile bind -target=android -o soundcloud.aar

    - name: Upload AAR
      uses: actions/upload-artifact@v2
      with:
        name: soundcloud-android
        path: soundcloud-api/soundcloud.aar
