name: Build Go Android Library

on:
  workflow_dispatch:   # Manual trigger

jobs:
  build:
    name: Build Android Library
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13'

      # Step 2: Check out the repository code
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # Step 3: Set up Android SDK and NDK using the official Google action
      - name: Set up Android SDK and NDK
        uses: google-github-actions/setup-android-sdk@v2
        with:
          sdk-version: "30.0.3"     # SDK Build tools version
          ndk-version: "21.3.6528147"  # NDK version for GoMobile
          api-level: 21             # Minimum API level
          platform: android-21      # Install platform-21 for GoMobile support

      # Step 4: Install GoMobile
      - name: Install GoMobile
        run: |
          # Install GoMobile and initialize
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      # Step 5: Download dependencies for your Go project
      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...

      # Step 6: Build Go Android Library (AAR file)
      - name: Build Go Android Library (AAR)
        run: |
          gomobile bind -v -o mylibrary.aar .

      # Step 7: Run tests (Optional)
      - name: Run Go tests
        run: |
          go test -v ./soundcloudapi_test

      # Step 8: Upload the AAR file as an artifact
      - name: Upload AAR file
        uses: actions/upload-artifact@v3
        with:
          name: android-library
          path: mylibrary.aar
