name: Build Go Android Library

on:
  workflow_dispatch:   # Manual trigger

jobs:
  build:
    name: Build Android Library
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13'

      # Step 2: Check out the repository code
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # Step 3: Set up Android SDK and NDK using setup-android action
      - name: Set up Android SDK and NDK
        uses: reactions/setup-android@v2
        with:
          api-level: 21          # Minimum API level required (21 and above for GoMobile)
          build-tools-version: 30.0.3  # You can update this version
          ndk-version: 21.3.6528147   # Required NDK version for GoMobile

      # Step 4: Install GoMobile
      - name: Install GoMobile
        run: |
          # Install GoMobile and initialize
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      # Step 5: Download dependencies for your Go project
      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...

      # Step 6: Build Go Android Library (AAR file)
      - name: Build Go Android Library (AAR)
        run: |
          gomobile bind -v -o mylibrary.aar .

      # Step 7: Run tests (Optional)
      - name: Run Go tests
        run: |
          go test -v ./soundcloudapi_test

      # Step 8: Upload the AAR file as an artifact
      - name: Upload AAR file
        uses: actions/upload-artifact@v3
        with:
          name: android-library
          path: mylibrary.aar
